version: "3.1"

services:
  node:
    build: ./code
    command: npm start
    volumes:
      - ./code/:/code/
      - /code/node_modules
    ports:
      - 3000:3000
    depends_on:
      - mysql_db
    links:
      - mysql_db

  mysql_db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: course1
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - 3306:3306

volumes:
  db_data: {}
